In [1]:
import os
print(os.getcwd())

C:\Users\demir

In [3]:
import pandas as pd

train = pd.read_csv("train.csv")
test = pd.read_csv("test_x.csv")
sample_submission = pd.read_csv("sample_submission.csv")

In [5]:
import pandas as pd
import numpy as np

train = pd.read_csv("train.csv")
test = pd.read_csv("test_x.csv")
sample_submission = pd.read_csv("sample_submission.csv")

print("Train shape:", train.shape)
print("Test shape:", test.shape)
print("Sample submission shape:", sample_submission.shape)

train.head()

Train shape: (56000, 24)
Test shape: (24000, 23)
Sample submission shape: (2, 2)

,id,yas,cinsiyet,meslek,vucut_kitle_indeksi,ulke,rem_yuzdesi,derin_uyku_yuzdesi,uykuya_dalma_suresi_dk,gecelik_uyanma_sayisi,...,stres_skoru,gunluk_calisma_saati,kronotip,ruh_sagligi_durumu,dinlenik_nabiz_bpm,oda_sicakligi_celsius,hafta_sonu_uyku_farki_saat,mevsim,gun_tipi,bilissel_performans_skoru
0,1,34,Erkek,Saglik Personeli,31.470103,Cin,14.431210,14.645436,27,7,...,9.922976,10.045274,Sabah insani,Anksiyete ve depresyon,78,18.962436,-0.074140,Sonbahar-Kis,Hafta ici,0.136441
1,2,32,Kadin,Muhendis,30.981394,Amerika,21.771870,27.220360,20,4,...,6.626400,6.319245,Gece insani,Saglikli,76,21.225666,0.942672,Sonbahar-Kis,Hafta ici,5.848312
2,3,39,Erkek,Ev Hanimi,21.533898,Spain,18.178857,25.530104,33,7,...,6.093566,3.824463,Notr,Depresyon,66,18.482409,1.239886,Ilkbahar-Yaz,Hafta sonu,6.828276
3,4,40,Kadin,Egitimci,23.310749,Yeni Zelanda,21.438151,15.891188,21,2,...,3.168185,4.597316,Gece insani,Saglikli,60,21.862235,0.727695,Sonbahar-Kis,Hafta sonu,8.144649
4,5,36,Kadin,NaN,NaN,Portekiz,25.468018,16.356738,21,8,...,7.198574,3.189120,Notr,Anksiyete ve depresyon,74,19.223195,-0.223402,Sonbahar-Kis,Hafta ici,0.431423

In [7]:
train.isnull().sum().sort_values(ascending=False)

kronotip                       1968
vucut_kitle_indeksi            1752
stres_skoru                    1715
uyku_oncesi_kafein_mg          1463
meslek                         1378
ruh_sagligi_durumu             1096
id                                0
gun_tipi                          0
mevsim                            0
hafta_sonu_uyku_farki_saat        0
oda_sicakligi_celsius             0
dinlenik_nabiz_bpm                0
gunluk_calisma_saati              0
gunluk_adim_sayisi                0
sekerleme_suresi_dk               0
yas                               0
uyku_oncesi_ekran_suresi_dk       0
gecelik_uyanma_sayisi             0
uykuya_dalma_suresi_dk            0
derin_uyku_yuzdesi                0
rem_yuzdesi                       0
ulke                              0
cinsiyet                          0
bilissel_performans_skoru         0
dtype: int64

In [9]:
numeric_cols = [
    "vucut_kitle_indeksi",
    "stres_skoru",
    "uyku_oncesi_kafein_mg"
]

for col in numeric_cols:
    median_value = train[col].median()

    train[col].fillna(median_value, inplace=True)
    test[col].fillna(median_value, inplace=True)

C:\Users\demir\AppData\Local\Temp\ipykernel_62124\3562083018.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train[col].fillna(median_value, inplace=True)
C:\Users\demir\AppData\Local\Temp\ipykernel_62124\3562083018.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test[col].fillna(median_value, inplace=True)

In [11]:
numeric_cols = [
    "vucut_kitle_indeksi",
    "stres_skoru",
    "uyku_oncesi_kafein_mg"
]

for col in numeric_cols:
    median_value = train[col].median()

    train[col] = train[col].fillna(median_value)
    test[col] = test[col].fillna(median_value)

In [13]:
categorical_fill_cols = [
    "kronotip",
    "meslek",
    "ruh_sagligi_durumu"
]

for col in categorical_fill_cols:
    train[col] = train[col].fillna("Bilinmiyor")
    test[col] = test[col].fillna("Bilinmiyor")

In [15]:
train.isnull().sum()

id                             0
yas                            0
cinsiyet                       0
meslek                         0
vucut_kitle_indeksi            0
ulke                           0
rem_yuzdesi                    0
derin_uyku_yuzdesi             0
uykuya_dalma_suresi_dk         0
gecelik_uyanma_sayisi          0
uyku_oncesi_kafein_mg          0
uyku_oncesi_ekran_suresi_dk    0
gunluk_adim_sayisi             0
sekerleme_suresi_dk            0
stres_skoru                    0
gunluk_calisma_saati           0
kronotip                       0
ruh_sagligi_durumu             0
dinlenik_nabiz_bpm             0
oda_sicakligi_celsius          0
hafta_sonu_uyku_farki_saat     0
mevsim                         0
gun_tipi                       0
bilissel_performans_skoru      0
dtype: int64

In [17]:
train["uyku_kalitesi"] = (
    train["rem_yuzdesi"] +
    train["derin_uyku_yuzdesi"]
) / 2

test["uyku_kalitesi"] = (
    test["rem_yuzdesi"] +
    test["derin_uyku_yuzdesi"]
) / 2

In [19]:
train["uyku_bozulma_skoru"] = (
    train["gecelik_uyanma_sayisi"] *
    train["uykuya_dalma_suresi_dk"]
)

test["uyku_bozulma_skoru"] = (
    test["gecelik_uyanma_sayisi"] *
    test["uykuya_dalma_suresi_dk"]
)

In [21]:
train["ekran_kafein_etkisi"] = (
    train["uyku_oncesi_ekran_suresi_dk"] *
    train["uyku_oncesi_kafein_mg"]
)

test["ekran_kafein_etkisi"] = (
    test["uyku_oncesi_ekran_suresi_dk"] *
    test["uyku_oncesi_kafein_mg"]
)

In [23]:
categorical_cols = [
    "cinsiyet",
    "meslek",
    "ulke",
    "kronotip",
    "ruh_sagligi_durumu",
    "mevsim",
    "gun_tipi"
]

In [25]:
X = train.drop(["bilissel_performans_skoru"], axis=1)
y = train["bilissel_performans_skoru"]

X_test = test.copy()

In [27]:
from sklearn.model_selection import train_test_split

X_train, X_valid, y_train, y_valid = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [29]:
!pip install catboost

Collecting catboost
  Downloading catboost-1.2.10-cp312-cp312-win_amd64.whl.metadata (1.5 kB)
Collecting graphviz (from catboost)
  Downloading graphviz-0.21-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: matplotlib in c:\users\demir\anaconda3\lib\site-packages (from catboost) (3.9.2)
Requirement already satisfied: numpy<3.0,>=1.16.0 in c:\users\demir\anaconda3\lib\site-packages (from catboost) (1.26.4)
Requirement already satisfied: pandas<4.0,>=0.24 in c:\users\demir\anaconda3\lib\site-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in c:\users\demir\anaconda3\lib\site-packages (from catboost) (1.13.1)
Requirement already satisfied: plotly in c:\users\demir\anaconda3\lib\site-packages (from catboost) (5.24.1)
Requirement already satisfied: six in c:\users\demir\anaconda3\lib\site-packages (from catboost) (1.16.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\demir\anaconda3\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\demir\anaconda3\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\demir\anaconda3\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2023.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\demir\anaconda3\lib\site-packages (from matplotlib->catboost) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\demir\anaconda3\lib\site-packages (from matplotlib->catboost) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\demir\anaconda3\lib\site-packages (from matplotlib->catboost) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\demir\anaconda3\lib\site-packages (from matplotlib->catboost) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\demir\anaconda3\lib\site-packages (from matplotlib->catboost) (24.1)
Requirement already satisfied: pillow>=8 in c:\users\demir\anaconda3\lib\site-packages (from matplotlib->catboost) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\demir\anaconda3\lib\site-packages (from matplotlib->catboost) (3.1.2)
Requirement already satisfied: tenacity>=6.2.0 in c:\users\demir\anaconda3\lib\site-packages (from plotly->catboost) (8.2.3)
Downloading catboost-1.2.10-cp312-cp312-win_amd64.whl (100.2 MB)
   ---------------------------------------- 0.0/100.2 MB ? eta -:--:--
   ---------------------------------------- 0.8/100.2 MB 4.2 MB/s eta 0:00:24
    --------------------------------------- 1.8/100.2 MB 5.0 MB/s eta 0:00:20
   - -------------------------------------- 2.9/100.2 MB 5.2 MB/s eta 0:00:19
   - -------------------------------------- 4.2/100.2 MB 5.3 MB/s eta 0:00:18
   -- ------------------------------------- 5.2/100.2 MB 5.5 MB/s eta 0:00:18
   -- ------------------------------------- 6.6/100.2 MB 5.5 MB/s eta 0:00:17
   --- ------------------------------------ 7.9/100.2 MB 5.7 MB/s eta 0:00:17
   --- ------------------------------------ 9.2/100.2 MB 5.8 MB/s eta 0:00:16
   ---- ----------------------------------- 10.2/100.2 MB 5.8 MB/s eta 0:00:16
   ---- ----------------------------------- 11.8/100.2 MB 5.9 MB/s eta 0:00:15
   ----- ---------------------------------- 12.8/100.2 MB 5.8 MB/s eta 0:00:15
   ----- ---------------------------------- 13.9/100.2 MB 5.8 MB/s eta 0:00:15
   ----- ---------------------------------- 14.9/100.2 MB 5.8 MB/s eta 0:00:15
   ------ --------------------------------- 16.3/100.2 MB 5.8 MB/s eta 0:00:15
   ------- -------------------------------- 17.6/100.2 MB 5.8 MB/s eta 0:00:15
   ------- -------------------------------- 18.6/100.2 MB 5.8 MB/s eta 0:00:15
   ------- -------------------------------- 19.9/100.2 MB 5.8 MB/s eta 0:00:14
   -------- ------------------------------- 21.0/100.2 MB 5.8 MB/s eta 0:00:14
   -------- ------------------------------- 22.3/100.2 MB 5.8 MB/s eta 0:00:14
   --------- ------------------------------ 23.6/100.2 MB 5.8 MB/s eta 0:00:14
   --------- ------------------------------ 24.9/100.2 MB 5.8 MB/s eta 0:00:13
   ---------- ----------------------------- 26.0/100.2 MB 5.8 MB/s eta 0:00:13
   ---------- ----------------------------- 27.3/100.2 MB 5.8 MB/s eta 0:00:13
   ----------- ---------------------------- 28.3/100.2 MB 5.8 MB/s eta 0:00:13
   ----------- ---------------------------- 29.6/100.2 MB 5.8 MB/s eta 0:00:13
   ------------ --------------------------- 30.9/100.2 MB 5.8 MB/s eta 0:00:12
   ------------ --------------------------- 32.0/100.2 MB 5.9 MB/s eta 0:00:12
   ------------- -------------------------- 33.3/100.2 MB 5.9 MB/s eta 0:00:12
   ------------- -------------------------- 34.6/100.2 MB 5.9 MB/s eta 0:00:12
   -------------- ------------------------- 35.9/100.2 MB 5.9 MB/s eta 0:00:11
   -------------- ------------------------- 37.5/100.2 MB 5.9 MB/s eta 0:00:11
   --------------- ------------------------ 38.8/100.2 MB 5.9 MB/s eta 0:00:11
   --------------- ------------------------ 39.8/100.2 MB 5.9 MB/s eta 0:00:11
   ---------------- ----------------------- 41.2/100.2 MB 5.9 MB/s eta 0:00:10
   ---------------- ----------------------- 42.5/100.2 MB 5.9 MB/s eta 0:00:10
   ----------------- ---------------------- 43.3/100.2 MB 5.9 MB/s eta 0:00:10
   ----------------- ---------------------- 44.0/100.2 MB 5.8 MB/s eta 0:00:10
   ----------------- ---------------------- 44.3/100.2 MB 5.8 MB/s eta 0:00:10
   ----------------- ---------------------- 45.1/100.2 MB 5.7 MB/s eta 0:00:10
   ------------------ --------------------- 45.9/100.2 MB 5.6 MB/s eta 0:00:10
   ------------------ --------------------- 46.1/100.2 MB 5.6 MB/s eta 0:00:10
   ------------------ --------------------- 46.1/100.2 MB 5.6 MB/s eta 0:00:10
   ------------------ --------------------- 46.4/100.2 MB 5.3 MB/s eta 0:00:11
   ------------------ --------------------- 46.4/100.2 MB 5.3 MB/s eta 0:00:11
   ------------------ --------------------- 46.9/100.2 MB 5.1 MB/s eta 0:00:11
   ------------------- -------------------- 47.7/100.2 MB 5.1 MB/s eta 0:00:11
   ------------------- -------------------- 48.5/100.2 MB 5.1 MB/s eta 0:00:11
   ------------------- -------------------- 49.5/100.2 MB 5.0 MB/s eta 0:00:11
   -------------------- ------------------- 50.6/100.2 MB 5.0 MB/s eta 0:00:10
   -------------------- ------------------- 51.4/100.2 MB 5.0 MB/s eta 0:00:10
   --------------------- ------------------ 52.7/100.2 MB 5.1 MB/s eta 0:00:10
   --------------------- ------------------ 53.7/100.2 MB 5.1 MB/s eta 0:00:10
   --------------------- ------------------ 55.1/100.2 MB 5.1 MB/s eta 0:00:09
   ---------------------- ----------------- 56.1/100.2 MB 5.1 MB/s eta 0:00:09
   ---------------------- ----------------- 57.1/100.2 MB 5.1 MB/s eta 0:00:09
   ----------------------- ---------------- 58.5/100.2 MB 5.1 MB/s eta 0:00:09
   ----------------------- ---------------- 59.5/100.2 MB 5.1 MB/s eta 0:00:08
   ------------------------ --------------- 60.8/100.2 MB 5.1 MB/s eta 0:00:08
   ------------------------ --------------- 61.9/100.2 MB 5.1 MB/s eta 0:00:08
   ------------------------- -------------- 63.2/100.2 MB 5.1 MB/s eta 0:00:08
   ------------------------- -------------- 64.2/100.2 MB 5.1 MB/s eta 0:00:07
   -------------------------- ------------- 65.5/100.2 MB 5.2 MB/s eta 0:00:07
   -------------------------- ------------- 66.6/100.2 MB 5.2 MB/s eta 0:00:07
   -------------------------- ------------- 67.6/100.2 MB 5.2 MB/s eta 0:00:07
   --------------------------- ------------ 68.4/100.2 MB 5.1 MB/s eta 0:00:07
   --------------------------- ------------ 69.2/100.2 MB 5.1 MB/s eta 0:00:07
   ---------------------------- ----------- 70.3/100.2 MB 5.1 MB/s eta 0:00:06
   ---------------------------- ----------- 71.3/100.2 MB 5.1 MB/s eta 0:00:06
   ---------------------------- ----------- 72.6/100.2 MB 5.1 MB/s eta 0:00:06
   ----------------------------- ---------- 73.7/100.2 MB 5.1 MB/s eta 0:00:06
   ----------------------------- ---------- 75.0/100.2 MB 5.2 MB/s eta 0:00:05
   ------------------------------ --------- 76.3/100.2 MB 5.2 MB/s eta 0:00:05
   ------------------------------ --------- 77.3/100.2 MB 5.2 MB/s eta 0:00:05
   ------------------------------- -------- 78.6/100.2 MB 5.2 MB/s eta 0:00:05
   ------------------------------- -------- 79.7/100.2 MB 5.2 MB/s eta 0:00:04
   -------------------------------- ------- 81.0/100.2 MB 5.2 MB/s eta 0:00:04
   -------------------------------- ------- 82.3/100.2 MB 5.2 MB/s eta 0:00:04
   --------------------------------- ------ 83.4/100.2 MB 5.2 MB/s eta 0:00:04
   --------------------------------- ------ 84.4/100.2 MB 5.2 MB/s eta 0:00:04
   ---------------------------------- ----- 85.7/100.2 MB 5.2 MB/s eta 0:00:03
   ---------------------------------- ----- 86.8/100.2 MB 5.2 MB/s eta 0:00:03
   ----------------------------------- ---- 88.1/100.2 MB 5.2 MB/s eta 0:00:03
   ----------------------------------- ---- 89.4/100.2 MB 5.3 MB/s eta 0:00:03
   ------------------------------------ --- 90.7/100.2 MB 5.3 MB/s eta 0:00:02
   ------------------------------------ --- 92.0/100.2 MB 5.3 MB/s eta 0:00:02
   ------------------------------------- -- 93.3/100.2 MB 5.3 MB/s eta 0:00:02
   ------------------------------------- -- 94.6/100.2 MB 5.3 MB/s eta 0:00:02
   -------------------------------------- - 95.7/100.2 MB 5.3 MB/s eta 0:00:01
   -------------------------------------- - 96.7/100.2 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------  97.8/100.2 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------  98.8/100.2 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------  100.1/100.2 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------  100.1/100.2 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------  100.1/100.2 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------  100.1/100.2 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------  100.1/100.2 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------  100.1/100.2 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------  100.1/100.2 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------  100.1/100.2 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------  100.1/100.2 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------  100.1/100.2 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------  100.1/100.2 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------- 100.2/100.2 MB 4.8 MB/s eta 0:00:00
Downloading graphviz-0.21-py3-none-any.whl (47 kB)
Installing collected packages: graphviz, catboost
Successfully installed catboost-1.2.10 graphviz-0.21

In [31]:
from catboost import CatBoostRegressor
from sklearn.metrics import mean_squared_error
import numpy as np

model = CatBoostRegressor(
    iterations=1000,
    learning_rate=0.05,
    depth=6,
    loss_function="RMSE",
    verbose=100
)

model.fit(
    X_train,
    y_train,
    cat_features=categorical_cols,
    eval_set=(X_valid, y_valid)
)

0:	learn: 2.1698902	test: 2.1808045	best: 2.1808045 (0)	total: 491ms	remaining: 8m 10s
100:	learn: 1.2345742	test: 1.2507004	best: 1.2507004 (100)	total: 13s	remaining: 1m 55s
200:	learn: 1.2110149	test: 1.2322213	best: 1.2322213 (200)	total: 24.2s	remaining: 1m 36s
300:	learn: 1.2001917	test: 1.2281552	best: 1.2281552 (300)	total: 38.2s	remaining: 1m 28s
400:	learn: 1.1911568	test: 1.2260105	best: 1.2260105 (400)	total: 54.2s	remaining: 1m 20s
500:	learn: 1.1828847	test: 1.2246873	best: 1.2246754 (496)	total: 1m 6s	remaining: 1m 6s
600:	learn: 1.1747989	test: 1.2239555	best: 1.2239308 (598)	total: 1m 20s	remaining: 53.3s
700:	learn: 1.1673721	test: 1.2237718	best: 1.2236144 (682)	total: 1m 31s	remaining: 39.2s
800:	learn: 1.1595253	test: 1.2238305	best: 1.2236114 (730)	total: 1m 43s	remaining: 25.7s
900:	learn: 1.1517098	test: 1.2237711	best: 1.2236114 (730)	total: 1m 54s	remaining: 12.5s
999:	learn: 1.1439871	test: 1.2238852	best: 1.2236114 (730)	total: 2m 7s	remaining: 0us

bestTest = 1.223611426
bestIteration = 730

Shrink model to first 731 iterations.

CatBoostRegressor(depth=6, iterations=1000, learning_rate=0.05, loss_function='RMSE', verbose=100)

In [32]:
preds = model.predict(X_valid)

rmse = np.sqrt(mean_squared_error(y_valid, preds))

print("RMSE:", rmse)

RMSE: 1.2236114270856384

In [35]:
test_predictions = model.predict(X_test)

In [37]:
submission = pd.DataFrame({
    "id": test["id"],
    "bilissel_performans_skoru": test_predictions
})

In [39]:
submission.to_csv("submission.csv", index=False)

In [41]:
submission.head()

   id  bilissel_performans_skoru
0   1                   6.152252
1   2                   6.473926
2   3                   2.925895
3   4                   6.968092
4   5                   3.680088